import os
import sys
import colorama
from colorama import Fore

print(Fore.RED + '')
print('')
print('')
print('')
print('')
 
print ( '##########################################################')
print ( '#                                                        #')
print ( '#               INTRODUCTION                             #')
print ( '#                                                        #')
print ( '#       NAME :- GAUTAM KUMAR SINGH                       #')
print ( '#                                                        #')
print ( '#       USERNAME:- MRX                                   #')
print ( '#                                                        #')
print ( '#       JOIN DISCORD:- https://discord.gg/xxzvh9x8XV     #')
print ( '#                                                        #')
print ( '#       GIT HUB:- https://github.com/haymrx              #')
print ( '#                                                        #')
print ( '##########################################################')
print ('')
print ('')
print ('')
print (Fore.BLUE + '')
print (	          '   $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$')
print (		  '   $               							      $')
print (Fore.RED	+ '   $                             SYLLABUS OF HACKING                          $')
print(Fore.BLUE + '   $									      $')
print (		  '   $            MODULE 01: Introduction to Ethical Hacking 	      	      $')
print (		  '   $                                                                          $')
print (		  '   $            MODULE 02: Footprinting and Reconnaissance		      $')
print (		  '   $                                                       		      $')
print (		  '   $            MODULE 03: Scanning Networks				      $')
print (		  '   $                                          				      $')
print (		  '   $            MODULE 04: Enumeration					      $')
print (		  '   $                        						      $')
print (		  '   $            MODULE 05: Vulnerability Analysis         		      $')
print (		  '   $                                    				      $')
print (		  '   $            MODULE 06: System Hacking				      $')
print (		  '   $									      $')
print (		  '   $            MODULE 07: Malware Threats			 	      $')
print (		  '   $									      $')
print (		  '   $            MODULE 08: Sniffing					      $')
print (		  '   $									      $')
print (		  '   $            MODULE 09: Social Engineering 				      $')
print (		  '   $									      $')
print (		  '   $            MODULE 10: Denial-of-Service				      $')
print(Fore.GREEN +'   $   									      $')
print (		  '   $            MODULE 11: Session Hijacking			      	      $')
print (		     '   $									      $')
print (		       '   $ 	     	MODULE 12: Evading IDS, Firewalls & Honeypots		      $')
print (		       '   $									      $')
print (		       '   $ 	     	MODULE 13: Hacking Web Servers				      $')
print (		       '   $									      $')
print (		       '   $ 	     	MODULE 14: Hacking Web Application		              $')
print ( 	       '   $      							       	      $')
print (		     '   $ 	     	MODULE 15: SQL Injection				      $')
print (		     '   $									      $')
print (		     '   $ 	     	MODULE 16: Hacking Wireless Networks			      $')
print (		     '   $									      $')
print (		     '   $ 	     	MODULE 17: Hacking Mobile Platforms                           $')
print (		     '   $									      $')
print (		     '   $ 	     	MODULE 18: IoT Hacking					      $')
print (		     '   $   									      $')
print (		     '   $ 	     	MODULE 19: Cloud Computing				      $')
print (		     '   $                                                                          $')
print (		     '   $ 	    	MODULE 20: Cryptography			                      $')
print (		     '   $									      $')
print (		     '   $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$')
	  


print(Fore.YELLOW +'')
print (' THANK YOU ')

